### PR TITLE
refactor: migrate from Axios to Fetch

### PR DESCRIPTION
**Pull request by liby**
## Changes

1. Replace Axios with Fetch
2. Here's a small refactor example that allows you to have logic from an API route reused in getServerSideProps. From Next.js [getServerSideProps](https://nextjs.org/docs/basic-features/data-fetching/get-server-side-props#getserversideprops-or-api-routes) documentation:

> It can be tempting to reach for an [API Route](https://nextjs.org/docs/api-routes/introduction) when you want to fetch data from the server, then call that API route from getServerSideProps. This is an unnecessary and inefficient approach, as it will cause an extra request to be made due to both getServerSideProps and API Routes running on the server.

## Other

There is some code that has not been removed, this is because I have only written a simple example. Do you need to weigh whether such a change is worth it? Has it become complicated?

### CODE REVIEW

**Review by tisonkun — APPROVED** [review]
Thanks for your contribution @liby ! Merging...

Although, I can see some error in the console, while it doesn't cause page fails to render:

```
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - SWC minify release candidate enabled. https://nextjs.link/swcmin
event - compiled client and server successfully in 279 ms (169 modules)
wait  - compiling / (client and server)...
event - compiled client and server successfully in 104 ms (199 modules)
(node:57149) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
wait  - compiling /_error (client and server)...
event - compiled client and server successfully in 38 ms (200 modules)
warn  - Fast Refresh had to perform a full reload. Read more: https://nextjs.org/docs/basic-features/fast-refresh#how-it-works
warn  - Fast Refresh had to perform a full reload. Read more: https://nextjs.org/docs/basic-features/fast-refresh#how-it-works
error - unhandledRejection: Error: aborted
    at connResetException (node:internal/errors:704:14)
    at abortIncoming (node:_http_server:696:17)
    at socketOnClose (node:_http_server:690:3)
    at Socket.emit (node:events:525:35)
    at TCP.<anonymous> (node:net:757:14) {
  code: 'ECONNRESET'
}
```

Also it doesn't render a `Loading` message before the server-side props returned now.

**Comment by liby** [comment]
> Although, I can see some error in the console, while it doesn't cause page fails to render:

 It's strange that I can't recreate it.
image

> Also it doesn't render a Loading message before the server-side props returned now.

~~`getStaticProps` runs at build time so there is no need for the loading screen since the data will always be available (statically generated). So we should remove the relevant code.~~

**Comment by tisonkun** [comment]
@liby Well, I cannot reproduce it now also. Let's forget that, lol.

> `getStaticProps`

We use [`getServerSideProps`](https://nextjs.org/docs/basic-features/data-fetching/get-server-side-props#getserversideprops-or-api-routes) in this patch I think. Shall we use `getStaticProps` instead?

**Comment by liby** [comment]
> We use [getServerSideProps](https://nextjs.org/docs/basic-features/data-fetching/get-server-side-props#getserversideprops-or-api-routes) in this patch I think. Shall we use getStaticProps instead?

 I misstated it.  I mistakenly thought you were asking me about `getStaticProps`.  I tried to modify the `_app.tsx` component to show loading status, but it didn't work.

**Pull request merged**
